In [1]:
# pip install numpy
import numpy as np  # np = numpy

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(-2,10)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [17]:
np.arange(3, 16, 2)

array([ 3,  5,  7,  9, 11, 13, 15])

In [19]:
np.array([(1,2,3),(4,5,6)]).shape

(2, 3)

In [27]:
np.array([1,2,3,4,5,6,7,8,9,10,11,
          12]).reshape(2
                       ,2,
                       3).reshape(
    12).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [28]:
np.arange(1000000).reshape(100,10000)

array([[     0,      1,      2, ...,   9997,   9998,   9999],
       [ 10000,  10001,  10002, ...,  19997,  19998,  19999],
       [ 20000,  20001,  20002, ...,  29997,  29998,  29999],
       ...,
       [970000, 970001, 970002, ..., 979997, 979998, 979999],
       [980000, 980001, 980002, ..., 989997, 989998, 989999],
       [990000, 990001, 990002, ..., 999997, 999998, 999999]])

In [30]:
a = np.array([10,10,10])
b = np.array([5,5,5])
a + b

array([15, 15, 15])

In [31]:
a - b

array([5, 5, 5])

In [32]:
a * b

array([50, 50, 50])

In [33]:
a / b

array([2., 2., 2.])

In [34]:
a % b

array([0, 0, 0], dtype=int32)

In [35]:
b % a

array([5, 5, 5], dtype=int32)

In [36]:
# Expresiones ()
a < 10

array([False, False, False])

In [37]:
a.dot(b)

150

In [38]:
np.dot(a,b)

150

In [39]:
a += 2

In [40]:
a

array([12, 12, 12])

In [41]:
a *= 2

In [42]:
a

array([24, 24, 24])

In [43]:
a = a + 2

In [44]:
a

array([26, 26, 26])

In [46]:
arreglo = np.arange(1,11)

In [48]:
arreglo.sum()

55

In [49]:
arreglo.min()

1

In [50]:
arreglo.max()

10

In [51]:
matriz = np.arange(12).reshape(3,4)

In [52]:
matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
matriz.sum(axis=0) # Columnas

array([12, 15, 18, 21])

In [55]:
matriz.sum(axis=1) # Filas

array([ 6, 22, 38])

In [57]:
notas = np.array([2,1,3,4,5,6,7,8,6,5,3,1,9])

In [58]:
notas.mean()

4.615384615384615

In [60]:
np.median(notas)

5.0

In [61]:
np.std(notas)

2.4663414679817532

In [62]:
np.var(notas)

6.0828402366863905

In [68]:
salarios = np.genfromtxt("./05_salarios.csv"
                        ,delimiter=",")

In [71]:
salarios.mean()

6.136363636363637

In [73]:
once = np.arange(11)**2

In [74]:
once

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [76]:
once[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [77]:
once[::3]

array([ 0,  9, 36, 81], dtype=int32)

In [78]:
once[::5]

array([  0,  25, 100], dtype=int32)

In [79]:
arreglo_split = np.arange(15)

In [83]:
print(np.split(arreglo_split,3))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]


In [85]:
print(np.split(arreglo_split,[2,6,9,13]))

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11, 12]), array([13, 14])]


In [88]:
salarios.sort()

In [89]:
salarios

array([ 0.,  1.,  1.,  2.,  2.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,
        7.,  8.,  8.,  9.,  9., 10., 12., 13., 13.])

In [104]:
salarios.sort()

In [105]:
salarios

array([ 0.,  1.,  1.,  2.,  2.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,
        7.,  8.,  8.,  9.,  9., 10., 12., 13., 13.])

In [112]:
arreglo_randomicos = np.random.randint(
    -10,18, size=20)

In [113]:
arreglo_randomicos

array([-7,  8,  3, -9, -9,  0, 12, 12, -6, -2, 15, 13, -2, 12,  1, 15, 12,
        9, -2,  7])